"use server"
import "server-only"
import { SignJWT, jwtVerify } from "jose"
import { isCorrect, posterById, posterByToken, posters, startRiddle, type Progress } from "@/lib/hunt"
import { logEvent, type HuntSummary } from "@/lib/log"

function getSecret() { return process.env.HUNT_SECRET ? new TextEncoder().encode(process.env.HUNT_SECRET) : null }
function setupError() { return { error: "Server setup error: HUNT_SECRET is not set." } }
async function sign(progress: Progress) { const secret = getSecret(); if (!secret) throw new Error("HUNT_SECRET is not set."); return new SignJWT(progress as unknown as Record<string, unknown>).setProtectedHeader({ alg: "HS256" }).setIssuedAt().sign(secret) }
export async function readProgress(token?: string) { const secret = getSecret(); if (!token || !secret) return null; try { const { payload } = await jwtVerify(token, secret, { algorithms: ["HS256"] }); return payload as unknown as Progress } catch (error) { console.error("[hunt] Failed to read progress token:", error); return null } }
function summary(progress: Progress, wrongGuesses = progress.wrongGuesses || 0): HuntSummary { return { teamId: progress.teamId, teamName: progress.teamName, startedAt: progress.startedAt, introSolvedAt: progress.introSolvedAt, solved: progress.solved.map((item, index) => ({ ...item, label: posterById(item.posterId)?.label || item.posterId, level: `${index + 1}${index === 0 ? "st" : index === 1 ? "nd" : "rd"}` })), wrongGuesses, finishedAt: progress.finishedAt, lastActivity: progress.finishedAt || progress.solved.at(-1)?.at || progress.introSolvedAt || progress.startedAt } }
function event(type: "team_created" | "intro_solved" | "poster_solved" | "wrong_answer" | "finished", progress: Progress, extra: Partial<{ posterId: string; label: string; level: string }>, wrongGuesses = 0) { const at = new Date().toISOString(); logEvent({ type, teamId: progress.teamId, teamName: progress.teamName, at, ...extra }, summary({ ...progress, ...(type === "finished" ? { finishedAt: at } : {}) }, wrongGuesses)) }
export async function startHunt(teamName: string) { if (!getSecret()) return setupError(); try { const name = teamName.trim(); if (name.length < 2 || name.length > 30) return { error: "Team name must be 2–30 characters." }; const progress: Progress = { teamId: crypto.randomUUID(), teamName: name, startedAt: new Date().toISOString(), solved: [] }; event("team_created", progress, {}); return { token: await sign(progress) } } catch (error) { console.error("[hunt] startHunt failed:", error); return { error: "Unable to start the hunt. Please try again." } } }
export async function submitIntroAnswer(progressToken: string, guess: string) { if (!getSecret()) return setupError(); try { const progress = await readProgress(progressToken); if (!progress) return { error: "Your saved progress couldn't be read. Tap here to start again." }; if (progress.introSolvedAt) return { token: progressToken }; if (!isCorrect(guess, startRiddle.acceptedAnswers)) { const updated = { ...progress, wrongGuesses: (progress.wrongGuesses || 0) + 1 }; event("wrong_answer", updated, {}, updated.wrongGuesses); return { error: "Not quite, try again." } } const nextPosterId = posters[Math.floor(Math.random() * posters.length)].id; const updated = { ...progress, introSolvedAt: new Date().toISOString(), nextPosterId }; event("intro_solved", updated, {}); return { token: await sign(updated), message: "Correct!", clue: posterById(nextPosterId)?.clue, nextPosterId } } catch (error) { console.error("[hunt] submitIntroAnswer failed:", error); return { error: "Unable to check your answer. Please try again." } } }
export async function submitAnswer(progressToken: string, posterToken: string, guess: string) { if (!getSecret()) return setupError(); try { const progress = await readProgress(progressToken); const poster = posterByToken(posterToken); if (!progress || !poster) return { error: "Your saved progress couldn't be read. Tap here to start again." }; if (!progress.introSolvedAt) return { needsIntro: true }; if (progress.finishedAt) return { finished: true }; if (progress.nextPosterId && progress.nextPosterId !== poster.id) return { error: "This isn't your next stop." }; if (progress.solved.some((item) => item.posterId === poster.id)) return { error: "You've already solved this one." }; if (!isCorrect(guess, poster.acceptedAnswers)) { const updated = { ...progress, wrongGuesses: (progress.wrongGuesses || 0) + 1 }; event("wrong_answer", updated, {}, updated.wrongGuesses); return { error: "Not quite, try again." } } const at = new Date().toISOString(); const solved = [...progress.solved, { posterId: poster.id, at }]; const remaining = posters.filter((item) => !solved.some((answer) => answer.posterId === item.id)); const nextPosterId = remaining.length ? remaining[Math.floor(Math.random() * remaining.length)].id : undefined; const updated: Progress = { ...progress, solved, nextPosterId, ...(remaining.length ? {} : { finishedAt: at }) }; const level = `${solved.length}${solved.length === 1 ? "st" : solved.length === 2 ? "nd" : "rd"}`; event("poster_solved", updated, { posterId: poster.id, label: poster.label, level }); if (!remaining.length) event("finished", updated, { posterId: poster.id, label: poster.label, level }); return { token: await sign(updated), finished: !remaining.length, clue: nextPosterId ? posterById(nextPosterId)?.clue : undefined } } catch (error) { console.error("[hunt] submitAnswer failed:", error); return { error: "Unable to check your answer. Please try again." } } }
export async function issueVerificationToken(token: string) { if (!getSecret()) return null; try { return (await readProgress(token)) ? token : null } catch (error) { console.error("[hunt] issueVerificationToken failed:", error); return null } }
