"use server"
import "server-only"
import { SignJWT, jwtVerify } from "jose"
import { isCorrect, posterById, posterByToken, posters, startRiddle, type Progress } from "@/lib/hunt"
function getSecret() { return process.env.HUNT_SECRET ? new TextEncoder().encode(process.env.HUNT_SECRET) : null }

function setupError() { return { error: "Server setup error: HUNT_SECRET is not set." } }
async function sign(progress: Progress) { const secret = getSecret(); if (!secret) throw new Error("HUNT_SECRET is not set."); return new SignJWT(progress as unknown as Record<string, unknown>).setProtectedHeader({ alg: "HS256" }).setIssuedAt().sign(secret) }
export async function readProgress(token?: string) { const secret = getSecret(); if (!token || !secret) return null; try { const { payload } = await jwtVerify(token, secret, { algorithms: ["HS256"] }); return payload as unknown as Progress } catch (error) { console.error("[hunt] Failed to read progress token:", error); return null } }
export async function startHunt(teamName: string) { if (!getSecret()) return setupError(); try { const name = teamName.trim(); if (name.length < 2 || name.length > 30) return { error: "Team name must be 2–30 characters." }; return { token: await sign({ teamName: name, startedAt: new Date().toISOString(), solved: [] }) } } catch (error) { console.error("[hunt] startHunt failed:", error); return { error: "Unable to start the hunt. Please try again." } } }
export async function submitIntroAnswer(progressToken: string, guess: string) { if (!getSecret()) return setupError(); try { const progress = await readProgress(progressToken); if (!progress) return { error: "Your saved progress couldn't be read. Tap here to start again." }; if (progress.introSolvedAt) return { token: progressToken }; if (!isCorrect(guess, startRiddle.acceptedAnswers)) return { error: "Not quite, try again." }; const updated = { ...progress, introSolvedAt: new Date().toISOString() }; return { token: await sign(updated), message: "Correct!" } } catch (error) { console.error("[hunt] submitIntroAnswer failed:", error); return { error: "Unable to check your answer. Please try again." } } }
export async function submitAnswer(progressToken: string, posterToken: string, guess: string) { if (!getSecret()) return setupError(); try { const progress = await readProgress(progressToken); const poster = posterByToken(posterToken); if (!progress || !poster) return { error: "Your saved progress couldn't be read. Tap here to start again." }; if (!progress.introSolvedAt) return { needsIntro: true }; if (progress.finishedAt) return { finished: true }; if (progress.nextPosterId && progress.nextPosterId !== poster.id) return { error: "This isn't your next stop." }; if (progress.solved.some((item) => item.posterId === poster.id)) return { error: "You've already solved this one." }; if (!isCorrect(guess, poster.acceptedAnswers)) return { error: "Not quite, try again." }; const solved = [...progress.solved, { posterId: poster.id, at: new Date().toISOString() }]; const remaining = posters.filter((item) => !solved.some((answer) => answer.posterId === item.id)); const nextPosterId = remaining.length ? remaining[Math.floor(Math.random() * remaining.length)].id : undefined; const updated: Progress = { ...progress, solved, nextPosterId, ...(remaining.length ? {} : { finishedAt: new Date().toISOString() }) }; return { token: await sign(updated), finished: !remaining.length, clue: nextPosterId ? posterById(nextPosterId)?.clue : undefined } } catch (error) { console.error("[hunt] submitAnswer failed:", error); return { error: "Unable to check your answer. Please try again." } } }
export async function issueVerificationToken(token: string) { if (!getSecret()) return null; try { return (await readProgress(token)) ? token : null } catch (error) { console.error("[hunt] issueVerificationToken failed:", error); return null } }
