"use client"

import { useEffect, useState } from "react"
import QRCode from "qrcode"
import confetti from "canvas-confetti"
import { Check, Clock3, Trophy } from "lucide-react"
import { Shell } from "@/components/hunt-app"

export function FinishedClient() { const [data, setData] = useState<any>(null); useEffect(() => { const token = localStorage.getItem("hunt-progress"); if (!token) return; fetch(`/api/progress?t=${encodeURIComponent(token)}`).then((r) => r.json()).then(async (value) => { setData(value); if (value.finished) { confetti({ particleCount: 140, spread: 85, origin: { y: 0.55 }, colors: ["#155EEF", "#7C3AED", "#F59E0B"] }); const url = `${window.location.origin}/staff/verify?t=${encodeURIComponent(token)}`; const qr = await QRCode.toDataURL(url, { width: 260, margin: 2, color: { dark: "#14213D", light: "#FFFFFF" } }); setData({ ...value, qr }) } }) }, []); if (!data) return <Shell><div className="h-80 animate-pulse rounded-3xl bg-white/60" /></Shell>; const started = new Date(data.progress.startedAt).getTime(); const finished = new Date(data.progress.finishedAt).getTime(); const minutes = Math.max(1, Math.round((finished - started) / 60000)); return <Shell><div className="text-center"><div className="mx-auto mb-5 flex size-20 items-center justify-center rounded-full bg-amber-100 text-amber-600 shadow-lg shadow-amber-200"><Trophy className="size-10" /></div><p className="text-sm font-bold uppercase tracking-[0.2em] text-purple-700">Hunt complete</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">You did it, {data.progress.teamName}!</h1><p className="mx-auto mt-4 max-w-md text-lg leading-8 text-slate-600">All three stops solved. Your team is officially in the running.</p></div><div className="mx-auto mt-8 max-w-sm rounded-3xl bg-white p-6 text-center shadow-xl shadow-blue-950/10"><div className="mx-auto flex size-[260px] items-center justify-center rounded-2xl bg-white">{data.qr && <img src={data.qr} alt="Verification QR code" className="size-[240px]" />}</div><div className="mt-5 flex items-center justify-center gap-2 font-bold text-[#155EEF]"><Clock3 /> Total time: {minutes} minute{minutes === 1 ? "" : "s"}</div></div><div className="mt-6 rounded-2xl bg-[#155EEF] p-5 text-center text-white"><p className="font-bold">Bring your whole team to a staff member and show this screen.</p><p className="mt-2 text-sm text-blue-100">The first 3 teams to finish win a prize!</p></div><p className="mt-6 flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><Check /> Three stops. One great team.</p></Shell> }
